// <auto-generated />
using System;
using CareerUp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CareerUp.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerUp.Models.Habilidade", b =>
                {
                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("HabilidadePrimaria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("habilidade_primaria");

                    b.Property<string>("HabilidadeSecundaria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("habilidade_secundaria");

                    b.Property<string>("HabilidadeTerciaria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("habilidade_terciaria");

                    b.HasKey("IdUsuario");

                    b.ToTable("tb_habilidade", (string)null);
                });

            modelBuilder.Entity("CareerUp.Models.LoginUsuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("login");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("NVARCHAR2(180)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("idx_login_usuario");

                    b.ToTable("tb_login_usuario", (string)null);
                });

            modelBuilder.Entity("CareerUp.Models.Recomendacao", b =>
                {
                    b.Property<long>("IdRecomendacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_recomendacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecomendacao"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_geracao");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("ResultadoIa")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("resultado_ia");

                    b.HasKey("IdRecomendacao");

                    b.HasIndex("DataGeracao")
                        .HasDatabaseName("idx_recomendacao_data");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_recomendacao_usuario");

                    b.ToTable("tb_recomendacao", (string)null);
                });

            modelBuilder.Entity("CareerUp.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("papel");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_email");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("CareerUp.Models.Habilidade", b =>
                {
                    b.HasOne("CareerUp.Models.Usuario", "Usuario")
                        .WithOne("Habilidade")
                        .HasForeignKey("CareerUp.Models.Habilidade", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CareerUp.Models.LoginUsuario", b =>
                {
                    b.HasOne("CareerUp.Models.Usuario", "Usuario")
                        .WithOne("LoginUsuario")
                        .HasForeignKey("CareerUp.Models.LoginUsuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CareerUp.Models.Recomendacao", b =>
                {
                    b.HasOne("CareerUp.Models.Usuario", "Usuario")
                        .WithMany("Recomendacoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CareerUp.Models.Usuario", b =>
                {
                    b.Navigation("Habilidade");

                    b.Navigation("LoginUsuario");

                    b.Navigation("Recomendacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
